# Generated by Django 4.1.7 on 2023-08-06 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=255, unique=True)),
                ("manufacturer", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                (
                    "departure_airport",
                    models.CharField(
                        choices=[
                            ("AG", "Solomon Islands"),
                            ("AN", "Nauru"),
                            ("AY", "Papua New Guinea"),
                            ("BG", "Greenland"),
                            ("BI", "Iceland"),
                            ("BK", "Kosovo"),
                            ("C", "Canada"),
                            ("DA", "Algeria"),
                            ("DB", "Benin"),
                            ("DF", "Burkina Faso"),
                            ("DG", "Ghana"),
                            ("DI", "Côte d'Ivoire"),
                            ("DN", "Nigeria"),
                            ("DR", "Niger"),
                            ("DT", "Tunisia"),
                            ("DX", "Togo"),
                            ("EB", "Belgium"),
                            ("ED", "Germany (civil)"),
                            ("EE", "Estonia"),
                            ("EF", "Finland"),
                            ("EG", "United Kingdom (and Crown Dependencies)"),
                            ("EH", "Netherlands"),
                            ("EI", "Ireland"),
                            ("EK", "Denmark and the Faroe Islands"),
                            ("EL", "Luxembourg"),
                            ("FZ", "Democratic Republic of the Congo"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "arrival_airport",
                    models.CharField(
                        choices=[
                            ("AG", "Solomon Islands"),
                            ("AN", "Nauru"),
                            ("AY", "Papua New Guinea"),
                            ("BG", "Greenland"),
                            ("BI", "Iceland"),
                            ("BK", "Kosovo"),
                            ("C", "Canada"),
                            ("DA", "Algeria"),
                            ("DB", "Benin"),
                            ("DF", "Burkina Faso"),
                            ("DG", "Ghana"),
                            ("DI", "Côte d'Ivoire"),
                            ("DN", "Nigeria"),
                            ("DR", "Niger"),
                            ("DT", "Tunisia"),
                            ("DX", "Togo"),
                            ("EB", "Belgium"),
                            ("ED", "Germany (civil)"),
                            ("EE", "Estonia"),
                            ("EF", "Finland"),
                            ("EG", "United Kingdom (and Crown Dependencies)"),
                            ("EH", "Netherlands"),
                            ("EI", "Ireland"),
                            ("EK", "Denmark and the Faroe Islands"),
                            ("EL", "Luxembourg"),
                            ("FZ", "Democratic Republic of the Congo"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="fly.aircraft",
                    ),
                ),
            ],
        ),
    ]
