# Generated by Django 4.1.7 on 2023-03-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fly", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="aicraft",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="fly.aircraft",
            ),
        ),
    ]
