# Generated by Django 4.1.7 on 2023-03-30 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fly", "0004_alter_aircraft_serial_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="arrivalat_time",
            new_name="arrival_time",
        ),
    ]
