# Generated by Django 4.1.7 on 2023-04-03 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fly", "0005_rename_arrivalat_time_flight_arrival_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="aicraft",
            new_name="aircraft",
        ),
    ]
